# Site settings
title: Fred Yankowski

email: fredcy@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  A simple static website with my stuff.

#url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: fredcy
#github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  dance:
    output: true
    
